/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import backend.sessionlogin;
import database.dbconnect;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rezan
 */
public class kelas extends javax.swing.JFrame {
    
    Connection conn;
    Statement stmt;
    ResultSet rs;
    int selectedid;
    
    dbconnect koneksi;
    
    DefaultTableModel dtm;
    ResultSetMetaData rsmd;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kelas.class.getName());

    /**
     * Creates new form kelas
     */
    public kelas() {
        if (!sessionlogin.islogin) {
            javax.swing.JOptionPane.showMessageDialog(this, "silahkan login dulu");
            new loginpage().setVisible(true);
            dispose();
            return;
        }
        getContentPane().removeAll();
        initComponents();
        
        koneksi = new dbconnect();
        conn = koneksi.getConnection();
        
        tblkelas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int selectedRow = tblkelas.getSelectedRow();

                if (selectedRow != -1) {

                    int modelRow = tblkelas.convertRowIndexToModel(selectedRow);

                    // ⬇ SIMPAN ID KE VARIABEL GLOBAL
                    selectedid = Integer.parseInt(
                        tblkelas.getModel().getValueAt(modelRow, 0).toString()
                    );

                    txtnamakelas.setText(
                        tblkelas.getModel().getValueAt(modelRow, 1).toString()
                    );
                }
            }
        });
        
        tampiltabel();
    }
    
    private DefaultTableModel buattabelmodel (ResultSet rs) throws SQLException {
        dtm = new DefaultTableModel();
        rsmd = rs.getMetaData();
        
        int jmlkolom = rsmd.getColumnCount();
        
        String [] namaKolom = new String[jmlkolom];
        for (int i = 0; i < jmlkolom; i++) {
            namaKolom[i] = rsmd.getColumnName(i + 1);
            } 
        dtm.setColumnIdentifiers(namaKolom);
            
            while (rs.next()) {
                String[] users = new String[jmlkolom];
                for (int i = 0; i < jmlkolom; i++) {
                    users [i] = rs.getString(i + 1);
                }
                dtm.addRow(users);
        }
            return dtm;
    }
    
    private boolean tampiltabel() {
        String sql = "SELECT ID, Class_Name FROM class";
          try {
              stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                      ResultSet.CONCUR_READ_ONLY);
              rs = stmt.executeQuery(sql);
              
              rs.last();
              if (rs.getRow() == 0){
                  JOptionPane.showMessageDialog(null, "data kelas tidak ada");
              } else {
                  rs.beforeFirst();
                  dtm = buattabelmodel(rs);
                  tblkelas.setModel(dtm);
                  
                  tblkelas.setModel(dtm);
                  tblkelas.getColumnModel().getColumn(0).setMinWidth(0);
                  tblkelas.getColumnModel().getColumn(0).setMaxWidth(0);
                  tblkelas.getColumnModel().getColumn(0).setWidth(0);
                  
                  tblkelas.setAutoCreateRowSorter(true);
              }
              return true;
          }catch (SQLException ex){
              JOptionPane.showMessageDialog(null, "error: " + ex.getMessage());
          }
          return false;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkelas = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        txtnamakelas = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(126, 27, 29));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Kelas: ");

        tblkelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblkelas);

        btnback.setBackground(new java.awt.Color(255, 119, 109));
        btnback.setForeground(new java.awt.Color(0, 153, 153));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/left-arrow.png"))); // NOI18N
        btnback.addActionListener(this::btnbackActionPerformed);

        btndelete.setBackground(new java.awt.Color(248, 231, 232));
        btndelete.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnupdate.setBackground(new java.awt.Color(248, 231, 232));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        btntambah.setBackground(new java.awt.Color(248, 231, 232));
        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list.png"))); // NOI18N
        btntambah.addActionListener(this::btntambahActionPerformed);

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("tambah");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ubah");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("hapus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btntambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtnamakelas)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnamakelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        dispose();
        dashboard fdashboard = new dashboard() ;
        fdashboard.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        if (selectedid != 0) {
            JOptionPane.showMessageDialog(this, 
                    "Anda sedang memilih data! klik tombol ubah jika ingin mengubah");
            return;
        }
        String namakelas = txtnamakelas.getText().trim();
        
        if (namakelas.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "nama kelas harus diisi");
            return;
        }
        String sql = "INSERT INTO class" 
                + "(Class_Name) VALUES (?)";
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, namakelas);
            
            int hasil = ps.executeUpdate();
            if (hasil > 0){
                JOptionPane.showMessageDialog(this, "data kelas berhasil ditambah");
                
                txtnamakelas.setText("");
         
                tampiltabel();
            } else{
                JOptionPane.showMessageDialog(this, 
                        "gagal menambahkan data kelas");
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "error insert: " + ex.getMessage());
        }finally {
            try {
                if (ps != null) ps.close();
            } 
            catch (SQLException e){
                
            }
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String namakelas = txtnamakelas.getText().trim();
        
        if (selectedid == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data kelas dari tabel terlebih dahulu!");
            return;
        }
        
        String sql = "UPDATE class SET Class_Name = ? WHERE ID = ?";
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(sql);
            ps.setString(1, namakelas);
            ps.setInt(2, selectedid);
            
            int hasil = ps.executeUpdate();
            if (hasil > 0){
                JOptionPane.showMessageDialog(this, "data kelas berhasil diubah");
                
                txtnamakelas.setText("");
                selectedid = 0;
                
                tampiltabel();
            } else{
                JOptionPane.showMessageDialog(this, 
                        "gagal mengubah data kelas");
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "error insert: " + ex.getMessage());
        }finally {
            try {
                if (ps != null) ps.close();
            } 
            catch (SQLException e){
                
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (selectedid == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data kelas dari tabel terlebih dahulu!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data kelas ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String sql = "DELETE FROM class WHERE ID = ?";
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(sql);
            ps.setInt(1, selectedid);

            int hasil = ps.executeUpdate();

            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, 
                        "Data kelas berhasil dihapus");

                txtnamakelas.setText("");
                selectedid = 0;

                tampiltabel();
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Gagal menghapus data kelas");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Error delete: " + ex.getMessage());
        } finally {
            try {
                if (ps != null) ps.close();
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kelas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkelas;
    private javax.swing.JTextField txtnamakelas;
    // End of variables declaration//GEN-END:variables
}
